version: "3.9"

services:
  php:
    image: php:8.2-apache
    container_name: php_docker
    ports:
      - "80:80"
    volumes:
      - ./php:/var/www/html
    networks:
      - php_docker-networks
    depends_on:
      - db

  db:
    image: mariadb:latest
    container_name: db_docker
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: db_docker
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - php_docker-networks

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
    networks:
      - php_docker-networks

networks:
  php_docker-networks:
    driver: bridge